blank_issues_enabled: false
contact_links:
  - name: è³ªå•ãƒ»ç›¸è«‡
    url:
    about: ä¿®æ­£ä¾é ¼ä»¥å¤–ã®è³ªå•ãƒ»ç›¸è«‡ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚

# issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š
defaults:
  - template: "revision_request.yml"
    name: "ğŸ“ ä¿®æ­£ä¾é ¼"
    about: "ä¿®æ­£ä¾é ¼ç”¨ã®issueã‚’ä½œæˆã—ã¾ã™ã€‚"
  - template: "coding.yml"
    name: "ğŸ’» ã‚³ãƒ¼ãƒ‡ã‚£ãƒ³ã‚°"
    about: "ä½œæ¥­ç”¨ã®issueã‚’ä½œæˆã—ã¾ã™ã€‚"
